[build]
  publish =  "dist/"
  command = "sh netlify-build.sh"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"
  for = "/*.mp3"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[context.production]
  environment = { }
